import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className="bg-gray-800 text-white py-4">
      <div className="container mx-auto flex justify-between items-center px-4 lg:px-0">
        {/* Логотип или название сайта */}
        <div className="text-xl font-bold">My Website</div>
        
        {/* Блоки меню */}
        <nav className="hidden lg:flex space-x-4">
          <a href="#" className="hover:text-gray-300">Home</a>
          <a href="#" className="hover:text-gray-300">About</a>
          <a href="#" className="hover:text-gray-300">Services</a>
          <a href="#" className="hover:text-gray-300">Portfolio</a>
          <a href="#" className="hover:text-gray-300">Contact</a>
        </nav>

        {/* Кнопки авторизации и регистрации */}
        <div className="hidden lg:flex space-x-4">
          <button className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600">Log In</button>
          <button className="px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600">Sign Up</button>
        </div>

        {/* Кнопка профиля */}
        <div className="lg:hidden">
          <button className="px-4 py-2 bg-gray-700 text-white rounded hover:bg-gray-600">Profile</button>
        </div>

        {/* Иконка для мобильного меню (если необходимо) */}
        {/* <div className="lg:hidden">
          <button>Меню</button>
        </div> */}
      </div>
    </header>
        {children}
        <footer className="bg-gray-800 text-white py-4">
      <div className="container mx-auto flex justify-between items-center px-4 lg:px-0">
        {/* Иконки социальных сетей */}
        <div className="flex space-x-4">
          <a href="#" className="text-xl">1</a>
          <a href="#" className="text-xl">2</a>
          <a href="#" className="text-xl">3</a>
          <a href="#" className="text-xl">4</a>
        </div>

        {/* Контактная информация */}
        <div className="text-sm">
          <p>Address: 123 Street Name, City, Country</p>
          <p>Email: example@example.com</p>
          <p>Phone: +1234567890</p>
        </div>
      </div>
    </footer>
        </body>
    </html>
  );
}
